// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
)

type Post struct {
	ID          int32        `json:"id"`
	Title       string       `json:"title"`
	Content     string       `json:"content"`
	Category    string       `json:"category"`
	CreatedDate sql.NullTime `json:"created_date"`
	UpdatedDate sql.NullTime `json:"updated_date"`
	Status      string       `json:"status"`
}
