// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: posts.sql

package db

import (
	"context"
	"database/sql"
)

const createPost = `-- name: CreatePost :execresult
INSERT INTO posts (
    title,
    content,
    category,
    status,
    created_date
) VALUES (
    ?, ?, ?, ?, ?
)
`

type CreatePostParams struct {
	Title       string       `json:"title"`
	Content     string       `json:"content"`
	Category    string       `json:"category"`
	Status      string       `json:"status"`
	CreatedDate sql.NullTime `json:"created_date"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPost,
		arg.Title,
		arg.Content,
		arg.Category,
		arg.Status,
		arg.CreatedDate,
	)
}

const deletePost = `-- name: DeletePost :execresult
DELETE FROM posts WHERE id=?
`

func (q *Queries) DeletePost(ctx context.Context, id int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePost, id)
}

const getPost = `-- name: GetPost :many
SELECT title, content, category, status FROM posts LIMIT ? OFFSET ?
`

type GetPostParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetPostRow struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	Category string `json:"category"`
	Status   string `json:"status"`
}

func (q *Queries) GetPost(ctx context.Context, arg GetPostParams) ([]GetPostRow, error) {
	rows, err := q.db.QueryContext(ctx, getPost, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostRow{}
	for rows.Next() {
		var i GetPostRow
		if err := rows.Scan(
			&i.Title,
			&i.Content,
			&i.Category,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostById = `-- name: GetPostById :one
SELECT title, content, category, status FROM posts where id=?
`

type GetPostByIdRow struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	Category string `json:"category"`
	Status   string `json:"status"`
}

func (q *Queries) GetPostById(ctx context.Context, id int32) (GetPostByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getPostById, id)
	var i GetPostByIdRow
	err := row.Scan(
		&i.Title,
		&i.Content,
		&i.Category,
		&i.Status,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :execresult
UPDATE posts SET title=?, content=?, category=?, status=?, updated_date=? WHERE id=?
`

type UpdatePostParams struct {
	Title       string       `json:"title"`
	Content     string       `json:"content"`
	Category    string       `json:"category"`
	Status      string       `json:"status"`
	UpdatedDate sql.NullTime `json:"updated_date"`
	ID          int32        `json:"id"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePost,
		arg.Title,
		arg.Content,
		arg.Category,
		arg.Status,
		arg.UpdatedDate,
		arg.ID,
	)
}
